name: Bug report
description: Report a problem in the Sola History app
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the issue?
      value: |
        1.
        2.
        3.
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: App version / Git commit
      description: If known, which version?
    validations:
      required: false
