name: Feature request
description: Suggest a new idea for Sola History
labels: ["enhancement"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What would you like to see?
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Any extra context, examples or mockups?
